### ISSUE TITLE
xmms2 hadn't stable release for 5+ years

### ISSUE THREAD

**Issue by sleep-walker** [xmms2/xmms2-stable#1]
xmms2 hadn't stable release for 5+ years

That means that it depends on libraries in ancient versions and it is hard to maintain in distribution. Please, consider release.

**Comment by dsvensson** [comment]
You're absolutely right. There's just some minor things blocking it. I think we've integrated all distro patches at least.

https://bugs.xmms2.org/view.php?id=2482

**Comment by sleep-walker** [comment]
I can only check openSUSE patches but these are not applied:
samba4 support - change location of headers - [xmms2-samba4-include-path.patch](https://build.opensuse.org/package/view_file/X11:lxde/xmms2/xmms2-samba4-include-path.patch)
typo in genre name - [xmms2-0.8-spelling-error.patch](https://build.opensuse.org/package/view_file/X11:lxde/xmms2/xmms2-0.8-spelling-error.patch)

distro specific but worth of mentinoning:
use _GNU_SOURCE -  [xmms2-0.8-fixwarnings.patch](https://build.opensuse.org/package/view_file/X11:lxde/xmms2/xmms2-0.8-fixwarnings.patch)
do not link against unused libraries - [xmms2-0.8-linker-flags.patch](https://build.opensuse.org/package/view_file/X11:lxde/xmms2/xmms2-0.8-linker-flags.patch)
don't use -O0 optimization level - [xmms2-0.8-no-O0.patch](https://build.opensuse.org/package/view_file/X11:lxde/xmms2/xmms2-0.8-no-O0.patch)
[xmms2-0.8-rpath.patch](https://build.opensuse.org/package/view_file/X11:lxde/xmms2/xmms2-0.8-rpath.patch)
manually set version in pkg-config file - [xmms2-pkgconfig.patch](https://build.opensuse.org/package/view_file/X11:lxde/xmms2/xmms2-pkgconfig.patch)

About the bug report you attach - I find it confusing. It was updated last time more than 5 years ago as well - is that still valid? Is that blocker for the release?

**Comment by dsvensson** [comment]
Could you prepare a pull request?

**Comment by dsvensson** [comment]
Against the xmms2-devel repo..

**Comment by dsvensson** [comment]
Wrt the issue, it is still valid. It hasn't been fixed. We could release without fixing it, which would just break the ices and ofa plugins I think.

**Comment by dsvensson** [comment]
Please re-open with pull request, or create a new issue with your distro fixes and pull request for that.

**Comment by funkycode** [comment]
Is the project dead?

**Comment by nesciens** [comment]
I'd say inactive rather than dead. Life has caught up to us, but we're still around.

@dsvensson, what do you think about a release of some cherrypicks onto -stable, just to try out the release machinery? A full release of all that's in devel seems daunting to me because of the migration from sqlite to s4, and the ice/ofa regression. I'd rather build some confidence with the process first.

**Comment by Malvineous** [comment]
How about an `-rc1` release candidate in that case?  Then it won't matter so much if things break.

**Comment by dsvensson** [comment]
@nesciens Humm... cherry picking towards stable, sounds like more work than fixing what's left. I should probably find some time and wrap my head around what's left again.

**Comment by ryandesign** [comment]
Can't understand why this issue was closed. It still hasn't been resolved. xmms2 now hasn't had a stable release in over 10 years.

**Comment by Malvineous** [comment]
It was closed because they were asking for PRs to merge in the outstanding bug fixes.  No point doing a release if the release will be broken.

**Comment by dsvensson** [comment]
I plan to retire in ~25 years or so, we'll get that release sooner or later :D
